language: ruby
rvm:
  - 1.9.3
  - 1.8.7
  - ree
  - jruby-19mode
  - jruby-18mode
gemfile:
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-3.0.x
  - gemfiles/Gemfile.rails-2.3.x
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: ree
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: jruby-18mode
      gemfile: gemfiles/Gemfile.rails-4.0.x
before_install:
  - gem update --system 1.8.25
notifications:
  email:
    - pilots@errplane.com
  on_success: change
  on_failure: always
script: bundle exec rake spec
