language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - 1.8.7
  - ree
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-3.0.x
  - gemfiles/Gemfile.rails-2.3.x
notifications:
  email:
    - mechanics@errplane.com
  on_success: change
  on_failure: always
script: rake spec
